-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT DISTINCT T2.ITEM_ID
    FROM (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE') T1 JOIN ITEM_TREE T2 ON T1.ITEM_ID = T2.PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC;