-- -- 코드를 입력하세요
-- SELECT f.FLAVOR
-- FROM FIRST_HALF f
-- JOIN ICECREAM_INFO i ON f.FLAVOR = i.FLAVOR
-- WHERE f.total_order > 3000
-- AND i.INGREDIENT_TYPE = 'fruit_based'
-- ORDER BY f.total_order DESC;

SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000 
AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC;

